set nocompatible

" musho oct 2019. lets do this
" followed guides by Doug Black and a Marchgg
" looked at a bunch of other peoples configs as well

" to put vundle in the sacamophagus, i need to paste some lines here:

"
" ***************************** BEGIN VUNDLE
"

filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" add other plugins like this: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Plugin 'easymotion/vim-easymotion'
Plugin 'vim-airline/vim-airline'

" ie 'github-user/project'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

"
" ***************************** END VUNDLE
"

" TO BEGIN
" there is a line at the very bottom and we need to tell vim that it's there?
set modelines=1

" leader key, it seems § is unused
let mapleader="§"

" utf-8 always always always
set encoding=utf-8

" -convenience variable- to add the powerline symbols into a neat varialbe
" let g:airline_powerline_fonts = 1


" Section Colours {{{

" decide colors per filetype
filetype on

" syntax colouring on
syntax on

" monokai color scheme
"  colorscheme molokai

" line numbers
set number
set relativenumber

" spaces allowed for line numbers
set numberwidth=4

" horizontal line where the cursor is
set cursorline

" show matching () characters (seems to be default?)
set showmatch

" }}}



" Section Formatting {{{

" no wrapping YES WRAPPING
set wrap

" number of spaces on screen per tab character
set tabstop=4

" convert tabs to spaces (when editing)
set expandtab

" how many spaces used for auto indents
set shiftwidth=4

" i dont actually know what these mean :(
set expandtab
set smartindent
set autoindent

" make it so that theres always a few lines at the bottonm of the screen - scrolloff = SCROLL OFFset
set scrolloff=15


" }}}



" Section Search {{{

    " search as you type
    set incsearch
    
    "   highlight searches
    set hlsearch

" }}}



" Section Keymaps {{{
    map <leader>rr :source ~/.vim/vimrc
" }}}



" this is a -modeline-, which is basically that you can set some vim-behaviour
" for a specific file? idk. this one is for folding.
" here it comes:
" vim:foldmethod=marker:foldlevel=0
